/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_png_PngPlayer */

#ifndef _Included_com_wind_ndk_png_PngPlayer
#define _Included_com_wind_ndk_png_PngPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_png_PngPlayer
 * Method:    nativeInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_wind_ndk_png_PngPlayer_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ndk_png_PngPlayer
 * Method:    nativeSetDataSource
 * Signature: (JLjava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_png_PngPlayer_nativeSetDataSource
  (JNIEnv *, jobject, jlong, jobject, jstring);

/*
 * Class:     com_wind_ndk_png_PngPlayer
 * Method:    nativeSurfaceCreated
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_png_PngPlayer_nativeSurfaceCreated
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_wind_ndk_png_PngPlayer
 * Method:    nativeSurfaceChanged
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_png_PngPlayer_nativeSurfaceChanged
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_wind_ndk_png_PngPlayer
 * Method:    nativeSurfaceDestroyed
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_png_PngPlayer_nativeSurfaceDestroyed
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_wind_ndk_png_PngPlayer
 * Method:    nativeRelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_png_PngPlayer_nativeRelease
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
